
services:
  database:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K42173008k
      POSTGRES_DB: prisma-basics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
   build: .
   container_name: express_api
   depends_on:
    - database
   environment:
    - DATABASE_URL=postgresql://postgres:K42173008k@database:5432/prisma-basics?schema=public
    - PORT=5000
   ports:
   - "5000:5000"
   volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
   command: ["sh", "-c", "npx prisma generate && node server.js"]
   networks:
     - app-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    restart: unless-stopped
    ports:
      - "9090:9090"
    
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - app-network
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_container
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  prometheus_data:
  postgres_data:
  grafana_data:

networks:
  app-network:
    driver: bridge



